"""empty message

Revision ID: 01a0487f3d4b
Revises: 3fa709de0f79
Create Date: 2021-09-09 17:44:50.820474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01a0487f3d4b'
down_revision = '3fa709de0f79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Gallery', 'titadle')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Gallery', sa.Column('titadle', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
