"""empty message

Revision ID: 101a4b5b790b
Revises: 
Create Date: 2021-09-09 16:40:40.449194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '101a4b5b790b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Gallery_photo_id_fkey', 'Gallery', type_='foreignkey')
    op.drop_column('Gallery', 'photo_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Gallery', sa.Column('photo_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('Gallery_photo_id_fkey', 'Gallery', 'Photo', ['photo_id'], ['id'])
    # ### end Alembic commands ###
