"""empty message

Revision ID: 2a3dfb9bd7a4
Revises: ca63fffe629f
Create Date: 2021-09-05 13:53:47.828125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a3dfb9bd7a4'
down_revision = 'ca63fffe629f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Photo', sa.Column('gallery_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Photo', 'Gallery', ['gallery_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Photo', type_='foreignkey')
    op.drop_column('Photo', 'gallery_id')
    # ### end Alembic commands ###
