"""empty message

Revision ID: 3fa709de0f79
Revises: 7af4ac0dd859
Create Date: 2021-09-09 17:44:35.559313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fa709de0f79'
down_revision = '7af4ac0dd859'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Gallery', sa.Column('titadle', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Gallery', 'titadle')
    # ### end Alembic commands ###
