"""empty message

Revision ID: 7af4ac0dd859
Revises: 92c560de8d15
Create Date: 2021-09-09 17:34:17.057955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7af4ac0dd859'
down_revision = '92c560de8d15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Gallery', 'ttitle')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Gallery', sa.Column('ttitle', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
